# -*- coding: utf-8 -*-
"""BreastCancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlgPfm1ggIazHuGIxeXZdrUCRVjHvwsN
"""

import pandas as pd

df = pd.read_csv("wdbc.data", header=None)
print(df.head())

with open("wdbc.names", "r") as f:
    content = f.read()

print(content)

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

columns = [
    "id", "diagnosis",
    "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
    "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean", "fractal_dimension_mean",
    "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
    "compactness_se", "concavity_se", "concave_points_se", "symmetry_se", "fractal_dimension_se",
    "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
    "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst", "fractal_dimension_worst"
]

df = pd.read_csv('wdbc.data', names=columns, header=None)

df = df.drop(columns=['id'])

df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

X_temp, X_global_test, y_temp, y_global_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

scaler = StandardScaler()
X_temp_scaled = pd.DataFrame(scaler.fit_transform(X_temp), columns=X.columns)
X_global_test_scaled = pd.DataFrame(scaler.transform(X_global_test), columns=X.columns)

y_temp = y_temp.reset_index(drop=True)
y_global_test = y_global_test.reset_index(drop=True)

#creating 4 clients
num_clients = 4
client_data = {}

indices = np.arange(len(X_temp_scaled))
np.random.seed(42)
np.random.shuffle(indices)
splits = np.array_split(indices, num_clients)

for i in range(num_clients):
    client_data[f"Client_{i+1}"] = {
        'X': X_temp_scaled.iloc[splits[i]],
        'y': y_temp.iloc[splits[i]]
    }
    print(f"Client {i+1} loaded with {len(splits[i])} samples.")

print("-" * 50)

# Federated Logistic Regression (True Parameter Averaging)
local_coefs = []
local_intercepts = []

for client_name, data in client_data.items():
    lr_client = LogisticRegression(max_iter=1000, random_state=42)
    lr_client.fit(data['X'], data['y'])
    local_coefs.append(lr_client.coef_)
    local_intercepts.append(lr_client.intercept_)

# Central Aggregation via FedAvg
fed_lr = LogisticRegression(max_iter=1000, random_state=42)

dummy_X = np.zeros((2, X_temp_scaled.shape[1]))
fed_lr.fit(dummy_X, [0, 1])

fed_lr.coef_ = np.mean(local_coefs, axis=0)
fed_lr.intercept_ = np.mean(local_intercepts, axis=0)


# Federated Tree Frameworks (Consensus Model Strategy)
fed_rf_clients = []
fed_xgb_clients = []

for client_name, data in client_data.items():
    # Train local models
    rf_client = RandomForestClassifier(n_estimators=50, random_state=42)
    rf_client.fit(data['X'], data['y'])
    fed_rf_clients.append(rf_client)

    xgb_client = XGBClassifier(n_estimators=50, eval_metric='logloss', random_state=42)
    xgb_client.fit(data['X'], data['y'])
    fed_xgb_clients.append(xgb_client)

def federated_tree_predict_proba(models, X_test):
    predictions = [model.predict_proba(X_test) for model in models]
    return np.mean(predictions, axis=0)


prob_lr = fed_lr.predict_proba(X_global_test_scaled)
prob_rf = federated_tree_predict_proba(fed_rf_clients, X_global_test_scaled)
prob_xgb = federated_tree_predict_proba(fed_xgb_clients, X_global_test_scaled)

# Perform Soft Ensemble Averaging
final_ensemble_prob = (prob_lr + prob_rf + prob_xgb) / 3.0
final_predictions = np.argmax(final_ensemble_prob, axis=1)


print(" FINAL GLOBAL EVALUATION RESULTS")

lr_preds = fed_lr.predict(X_global_test_scaled)
rf_preds = np.argmax(prob_rf, axis=1)
xgb_preds = np.argmax(prob_xgb, axis=1)

print(f"Federated Logistic Regression Accuracy : {accuracy_score(y_global_test, lr_preds) * 100:.2f}%")
print(f"Federated Random Forest Accuracy       : {accuracy_score(y_global_test, rf_preds) * 100:.2f}%")
print(f"Federated XGBoost Accuracy              : {accuracy_score(y_global_test, xgb_preds) * 100:.2f}%")
print("-" * 50)
print(f"FEDERATED SOFT ENSEMBLE ACCURACY       : {accuracy_score(y_global_test, final_predictions) * 100:.2f}%")
print("-" * 50)

print("\nClassification Report for Federated Ensemble:")
print(classification_report(y_global_test, final_predictions, target_names=['Benign', 'Malignant']))

pip install shap lime

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

# For Explainable AI
import shap
from lime import lime_tabular

columns = [
    "id", "diagnosis",
    "radius_mean", "texture_mean", "perimeter_mean", "area_mean", "smoothness_mean",
    "compactness_mean", "concavity_mean", "concave_points_mean", "symmetry_mean", "fractal_dimension_mean",
    "radius_se", "texture_se", "perimeter_se", "area_se", "smoothness_se",
    "compactness_se", "concavity_se", "concave_points_se", "symmetry_se", "fractal_dimension_se",
    "radius_worst", "texture_worst", "perimeter_worst", "area_worst", "smoothness_worst",
    "compactness_worst", "concavity_worst", "concave_points_worst", "symmetry_worst", "fractal_dimension_worst"
]

df = pd.read_csv('wdbc.data', names=columns, header=None)
df = df.drop(columns=['id'])
df['diagnosis'] = df['diagnosis'].map({'M': 1, 'B': 0})

X = df.drop(columns=['diagnosis'])
y = df['diagnosis']

X_temp, X_global_test, y_temp, y_global_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

scaler = StandardScaler()
X_temp_scaled = pd.DataFrame(scaler.fit_transform(X_temp), columns=X.columns)
X_global_test_scaled = pd.DataFrame(scaler.transform(X_global_test), columns=X.columns)

y_temp = y_temp.reset_index(drop=True)
y_global_test = y_global_test.reset_index(drop=True)

# Split into 4 clients (Silos)
num_clients = 4
client_data = {}
indices = np.arange(len(X_temp_scaled))
np.random.seed(42)
np.random.shuffle(indices)
splits = np.array_split(indices, num_clients)

for i in range(num_clients):
    client_data[f"Client_{i+1}"] = {
        'X': X_temp_scaled.iloc[splits[i]],
        'y': y_temp.iloc[splits[i]]
    }

local_coefs, local_intercepts = [], []
fed_rf_clients = []

for client_name, data in client_data.items():
    # Logistic Regression
    lr_client = LogisticRegression(max_iter=1000, random_state=42)
    lr_client.fit(data['X'], data['y'])
    local_coefs.append(lr_client.coef_)
    local_intercepts.append(lr_client.intercept_)

    # Random Forest (For Tree Consensus representation)
    rf_client = RandomForestClassifier(n_estimators=50, random_state=42)
    rf_client.fit(data['X'], data['y'])
    fed_rf_clients.append(rf_client)

# Construct Central Global Models
fed_lr = LogisticRegression(max_iter=1000, random_state=42)
dummy_X = np.zeros((2, X_temp_scaled.shape[1]))
fed_lr.fit(dummy_X, [0, 1])
fed_lr.coef_ = np.mean(local_coefs, axis=0)
fed_lr.intercept_ = np.mean(local_intercepts, axis=0)

representative_rf = fed_rf_clients[0] # Client 1 representation for Tree Explanations

print("Federated Framework models initialized. Beginning XAI computations...")

print("[SHAP] Generating Global & Local Explanations...")

# LinearSHAP on Federated Logistic Regression
explainer_shap_lr = shap.LinearExplainer(fed_lr, X_temp_scaled)
shap_values_lr = explainer_shap_lr(X_global_test_scaled)

# Plot 1: SHAP Global Feature Summary
plt.figure(figsize=(10, 5))
shap.summary_plot(shap_values_lr, X_global_test_scaled, show=False)
plt.title("SHAP Global Summary: Federated Logistic Regression", fontsize=14, pad=15)
plt.tight_layout()
plt.show()

# Plot 2: SHAP Local Waterfall for the first patient instance
plt.figure(figsize=(10, 4))
plt.title("SHAP Local Explanation (Patient 0)", fontsize=14, pad=15)
shap.plots.waterfall(shap_values_lr[0])
plt.show()

print("\n[LIME] Generating Local Instance Explanation...")

explainer_lime = lime_tabular.LimeTabularExplainer(
    training_data=np.array(X_temp_scaled),
    feature_names=X_temp_scaled.columns,
    class_names=['Benign', 'Malignant'],
    mode='classification',
    random_state=42
)

lime_exp = explainer_lime.explain_instance(
    data_row=X_global_test_scaled.iloc[0],
    predict_fn=fed_lr.predict_proba,
    num_features=10
)

# Plot 3: LIME Feature Attribution bar chart for the patient instance
plt.figure(figsize=(10, 5))
fig = lime_exp.as_pyplot_figure()
plt.title("LIME Local Explanation (Patient 0)", fontsize=14, pad=15)
plt.tight_layout()
plt.show()

print("-" * 60)
print("XAI Evaluation Complete. Compare SHAP's mathematical distribution to LIME's local neighborhood linear fit graphs above.")

import joblib
import os

os.makedirs("federated_breast_cancer_model", exist_ok=True)

joblib.dump(scaler, "federated_breast_cancer_model/feature_scaler.pkl")

joblib.dump(fed_lr, "federated_breast_cancer_model/fed_logistic_regression.pkl")

joblib.dump(fed_rf_clients, "federated_breast_cancer_model/fed_rf_clients.pkl")
joblib.dump(fed_xgb_clients, "federated_breast_cancer_model/fed_xgb_clients.pkl")

print("Successfully exported all federated architecture components and scalers!")

import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score

models_metadata = {
    "Federated Logistic Regression": {
        "preds": lr_preds,
        "probs": prob_lr[:, 1]
    },
    "Federated Random Forest": {
        "preds": rf_preds,
        "probs": prob_rf[:, 1]
    },
    "Federated XGBoost": {
        "preds": xgb_preds,
        "probs": prob_xgb[:, 1]
    }
}

federated_extended_results = []
for model_name, data in models_metadata.items():
    acc = accuracy_score(y_global_test, data["preds"]) * 100
    prec = precision_score(y_global_test, data["preds"]) * 100
    rec = recall_score(y_global_test, data["preds"]) * 100
    f1 = f1_score(y_global_test, data["preds"]) * 100
    auc = roc_auc_score(y_global_test, data["probs"])

    federated_extended_results.append({
        "Model": model_name,
        "Accuracy (%)": round(acc, 2),
        "Precision (%)": round(prec, 2),
        "Recall (%)": round(rec, 2),
        "F1-Score (%)": round(f1, 2),
        "ROC-AUC": round(auc, 4)
    })

# 3. Compile and print the publication-ready DataFrame format
metrics_df = pd.DataFrame(federated_extended_results)

print("\n" + "="*85)
print("             EXTENDED PERFORMANCE METRICS FOR FEDERATED GLOBAL MODELS")
print("="*85)
print(metrics_df.to_markdown(index=False))

from sklearn.metrics import roc_auc_score

ensemble_positive_probs = final_ensemble_prob[:, 1]

# Calculate the ROC-AUC score
ensemble_auc = roc_auc_score(y_global_test, ensemble_positive_probs)

print("=== FEDERATED SOFT ENSEMBLE ROC-AUC ===")
print(f"ROC-AUC Score: {ensemble_auc:.4f}")

import matplotlib.pyplot as plt
import numpy as np
models = ['LR', 'RF', 'XGB']
centralized_acc = [96.49, 97.37, 97.37]
federated_acc = [98.25, 95.61, 96.49]

x = np.arange(len(models))
width = 0.35

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif']
plt.rcParams['font.size'] = 10
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10
plt.rcParams['legend.fontsize'] = 10

fig, ax = plt.subplots(figsize=(5.5, 4), dpi=300)

rects1 = ax.bar(x - width/2, centralized_acc, width, label='Centralized',
                color='#4D4D4D', edgecolor='black', linewidth=0.8, hatch='//')
rects2 = ax.bar(x + width/2, federated_acc, width, label='Federated (FedAvg)',
                color='#E6E6E6', edgecolor='black', linewidth=0.8)

ax.set_ylabel('Accuracy (%)', fontweight='bold', labelpad=8)
ax.set_xlabel('Machine Learning Models', fontweight='bold', labelpad=8)
ax.set_xticks(x)
ax.set_xticklabels(models)
ax.set_ylim(85, 102)

ax.grid(axis='y', linestyle='--', alpha=0.5, zorder=0)
ax.set_axisbelow(True)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

ax.legend(loc='upper right', frameon=True, edgecolor='black', fancybox=False)

def autolabel(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}%',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 4),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=9, fontweight='medium')

autolabel(rects1)
autolabel(rects2)

plt.tight_layout()

plt.savefig('centralized_vs_federated_accuracy.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import shap

representative_model = fed_xgb_clients[0]
explainer_xgb = shap.TreeExplainer(representative_model)
shap_values_xgb = explainer_xgb(X_global_test_scaled)

plt.figure(figsize=(10, 6), dpi=300)

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif']

shap.plots.beeswarm(shap_values_xgb, max_display=15, show=False)

plt.title("SHAP Global Summary: Federated XGBoost Model", fontsize=12, fontweight='bold', pad=15)
plt.xlabel("SHAP Value (Impact on Model Output)", fontsize=11, fontweight='bold')
plt.tight_layout()

plt.savefig('federated_xgboost_shap_summary.png', dpi=300, bbox_inches='tight')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from lime import lime_tabular

correct_indices = np.where(lr_preds == y_global_test)[0]

if len(correct_indices) == 0:
    raise ValueError("No correctly classified instances found.")

selected_idx = correct_indices[0]
instance_to_explain = X_global_test_scaled.iloc[selected_idx]
true_label = y_global_test.iloc[selected_idx]
predicted_label = lr_preds[selected_idx]

class_names = ['Benign', 'Malignant']
print(f"Explaining Test Instance at Index: {selected_idx}")
print(f"True Label: {class_names[true_label]} | Predicted Label: {class_names[predicted_label]}\n")

explainer_lime = lime_tabular.LimeTabularExplainer(
    training_data=np.array(X_temp_scaled),
    feature_names=X_temp_scaled.columns,
    class_names=class_names,
    mode='classification',
    random_state=42
)

exp = explainer_lime.explain_instance(
    data_row=instance_to_explain,
    predict_fn=fed_lr.predict_proba,
    num_features=10
)

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif']

fig = exp.as_pyplot_figure()
plt.title(f"LIME Local Explanation (Correctly Classified Instance {selected_idx})", fontsize=12, fontweight='bold', pad=15)
plt.tight_layout()

plt.savefig('federated_lr_lime_explanation.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc

#ROC CURVES FOR INDIVIDUAL MODELS & SOFT VOTING ENSEMBLE
roc_data = {
    'Federated Logistic Regression': prob_lr[:, 1],
    'Federated Random Forest': prob_rf[:, 1],
    'Federated XGBoost': prob_xgb[:, 1],
    'Federated Soft Ensemble': final_ensemble_prob[:, 1]
}
plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.serif'] = ['Times New Roman', 'DejaVu Serif']
plt.rcParams['font.size'] = 10
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['axes.titlesize'] = 12
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10
plt.rcParams['legend.fontsize'] = 9

fig, ax = plt.subplots(figsize=(6, 4.5), dpi=300)

styles = {
    'Federated Logistic Regression': {'color': '#333333', 'linestyle': '--', 'linewidth': 1.2},
    'Federated Random Forest': {'color': '#666666', 'linestyle': '-.', 'linewidth': 1.2},
    'Federated XGBoost': {'color': '#999999', 'linestyle': ':', 'linewidth': 1.5},
    'Federated Soft Ensemble': {'color': '#000000', 'linestyle': '-', 'linewidth': 1.8}
}

for name, probs in roc_data.items():
    fpr, tpr, _ = roc_curve(y_global_test, probs)
    roc_auc = auc(fpr, tpr)

    ax.plot(fpr, tpr,
            label=f'{name} (AUC = {roc_auc:.4f})',
            color=styles[name]['color'],
            linestyle=styles[name]['linestyle'],
            linewidth=styles[name]['linewidth'])

ax.plot([0, 1], [0, 1], color='#B3B3B3', linestyle='--', linewidth=0.8, label='Random Classifier')

ax.set_xlim([-0.02, 1.02])
ax.set_ylim([-0.02, 1.02])
ax.set_xlabel('False Positive Rate (1 - Specificity)', fontweight='bold', labelpad=8)
ax.set_ylabel('True Positive Rate (Sensitivity)', fontweight='bold', labelpad=8)
ax.set_title('Receiver Operating Characteristic (ROC) Curves', fontsize=12, fontweight='bold', pad=15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.grid(True, linestyle='--', alpha=0.4, zorder=0)
ax.legend(loc='lower right', frameon=True, edgecolor='black', fancybox=False)
plt.tight_layout()
plt.savefig('federated_models_roc_curves.png', dpi=300, bbox_inches='tight')
plt.show()